---
title: "Asessment 1 (Part2)"
author: "Kris Chavez (s4591950)"
date: '2022-05-010'
output: 
  html_document:
      number_sections: true           
      toc: true                       #TOC = Table of COntents
      toc_depth: 2
      theme: readable                  #Added a theme to make the document more appealing
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Install.packages("tidyverse")
# Install.packages("rmarkdown")
library(tidyverse)
library(rmarkdown)
```


### Loading the dataset
As shown below, we have loaded the *data* in a **new** variable called 'fastfood'
```{r load the required CSV file}
# Set working the working directory to the data set provided by the lecturer
fastfood <- read.csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-09-04/fastfood_calories.csv")
```


### Saving a copy of the dataset
``` {r saving a  copy of the CSV file}
# Saving my data as a CSV file
write_csv(fastfood, "fastfood.csv")
fastfood_data<-read_csv("fastfood.csv")
```


### Display the oobservations that has more than 1000 calories
``` {r}
fastfood %>%                  # add a pipe
  filter(calories > 1000)     # greater than filter
```
### Arrange observations with more than 40 in total_fat and more than 80 in total_carb in the descending order and save them to a new variable (dataset) called 'dont_eat_this'


### 